const express = require('express')
const router = express.Router()
const openMeteo = require('../openMeteo')
const locations = require('../data/locations.json')


router.get('/assessment', async (req, res) => {
  try {
    const { lat, lon } = req.query
    if (!lat || !lon) return res.status(400).json({ error: 'lat and lon are required' })
    const weather = await openMeteo.getCurrentWeather(Number(lat), Number(lon))
    const risk = openMeteo.calculateFireRisk(weather)
    res.json({ risk, weather })
  } catch (err) {
    console.error(err.message || err)
    res.status(500).json({ error: 'Failed to compute risk' })
  }
})


router.get('/alerts', (req, res) => {
  const region = req.query.region || 'all'
 
  const alerts = [
    { 
      id: 'AL-2041',
      severity: 'critical',
      title: 'Wind-driven spread expected within 2 hours',
      location: 'Nilgiris, Tamil Nadu',
      updated: '12 mins ago',
      details: 'Gusts above 45 km/h aligned with slopes. Hold bulldozer line at sector 7 and deploy aerial support.',
      sectors: ['S-07', 'S-08'],
      resources: '2 crews, 1 tanker',
      region: 'South Asia'
    },
    { 
      id: 'AL-2037',
      severity: 'high',
      title: 'Dry lightning cluster forecast',
      location: 'Gadchiroli, Maharashtra',
      updated: '28 mins ago',
      details: '14 strikes recorded in last pass. Patrol teams to sweep forest compartments 11B-15D.',
      sectors: ['11B', '15D'],
      resources: 'Patrol group Bravo',
      region: 'Western Ghats'
    },
    { 
      id: 'AL-2021',
      severity: 'medium',
      title: 'Community smoke reports pending validation',
      location: 'Shimla, Himachal Pradesh',
      updated: '45 mins ago',
      details: 'Three separate 112 calls referencing visible smoke. Dispatch reconnaissance drone once ceiling clears.',
      sectors: ['North Ridge'],
      resources: 'Recon drone',
      region: 'Central India'
    }
  ]
  
  const filtered = region === 'all' 
    ? alerts 
    : alerts.filter(a => a.region && a.region.toLowerCase().includes(region.toLowerCase()))
  
  res.json({ alerts: filtered })
})


router.get('/zones', (req, res) => {
  const zones = locations.map(l => ({ id: l.id, name: l.name, region: l.region, center: [l.lat, l.lon], riskLevel: l.riskLevel }))
  res.json(zones)
})


router.get('/predictions', async (req, res) => {
  try {
    const { lat, lon, days } = req.query
    if (!lat || !lon) return res.status(400).json({ error: 'lat and lon are required' })
    const forecast = await openMeteo.getForecast(Number(lat), Number(lon), Number(days) || 3)
    const daily = forecast.daily || {}
    const predictions = (daily.time || []).map((t, idx) => {
      const tempMax = daily.temperature_2m_max ? daily.temperature_2m_max[idx] : null
      const temp = tempMax || 25
      const score = Math.min(100, Math.round((temp / 40) * 100))
      return { date: t, score, level: score > 70 ? 'High' : score > 40 ? 'Moderate' : 'Low' }
    })
    res.json(predictions)
  } catch (err) {
    console.error(err.message || err)
    res.status(500).json({ error: 'Failed to fetch predictions' })
  }
})


router.get('/statistics', (req, res) => {
  const highRiskCount = locations.filter(l => l.riskLevel === 'high').length
  const mediumRiskCount = locations.filter(l => l.riskLevel === 'medium').length
  const lowRiskCount = locations.filter(l => l.riskLevel === 'low').length
  
  res.json({ 
    totalZones: locations.length, 
    highRisk: highRiskCount,
    mediumRisk: mediumRiskCount,
    lowRisk: lowRiskCount,
    monthlyReports: 82,
    autoGenerated: 41,
    avgLeadTime: '18 min',
    coverage: '26 districts'
  })
})


router.get('/fire-hotspots', (req, res) => {
  const hotspots = [
    { id: 1, lat: 22.7, lon: 88.3, intensity: 0.9 },
    { id: 2, lat: 19.07, lon: 72.88, intensity: 0.6 }
  ]
  res.json(hotspots)
})

module.exports = router
