import { useState } from 'react'
import {
  Container,
  Box,
  Typography,
  Paper,
  Grid,
  Stack,
  Button,
  Chip,
  Table,
  TableHead,
  TableRow,
  TableCell,
  TableBody
} from '@mui/material'
import DownloadIcon from '@mui/icons-material/Download'
import PictureAsPdfIcon from '@mui/icons-material/PictureAsPdf'
import TimelineIcon from '@mui/icons-material/Timeline'
import MapIcon from '@mui/icons-material/Map'
import AssessmentIcon from '@mui/icons-material/Assessment'
import { RISK_COLORS } from '../theme'
import ChartComponent from '../components/ChartComponent'
import MapComponent from '../components/MapComponent'
import { useRiskStatistics } from '../hooks/useRisk'

const FALLBACK_STATS = {
  monthlyReports: 82,
  autoGenerated: 41,
  avgLeadTime: '18 min',
  coverage: '26 districts',
}

const RECENT_REPORTS = [
  { id: 'SIT-3175', region: 'Vidarbha', type: 'Operational', issued: 'Today 08:40', status: 'Delivered' },
  { id: 'SIT-3169', region: 'Nilgiris', type: 'Weather + Risk', issued: 'Today 06:10', status: 'Delivered' },
  { id: 'SIT-3151', region: 'Coorg', type: 'Suppression Plan', issued: 'Yesterday 21:45', status: 'Ack. pending' },
]

function Reports() {
  const [refreshKey, setRefreshKey] = useState(0)
  const { data, loading, error } = useRiskStatistics(true, refreshKey)
  const stats = data || FALLBACK_STATS

  const KPIs = [
    { label: 'Reports this month', value: stats.monthlyReports, icon: <AssessmentIcon sx={{ color: '#1976d2' }} /> },
    { label: 'Auto-generated', value: stats.autoGenerated, icon: <TimelineIcon sx={{ color: '#42a5f5' }} /> },
    { label: 'Average lead time', value: stats.avgLeadTime, icon: <MapIcon sx={{ color: '#26a69a' }} /> },
    { label: 'Coverage', value: stats.coverage, icon: <MapIcon sx={{ color: '#ef5350' }} /> },
  ]

  return (
    <Container maxWidth="xl" sx={{ py: 4, pb: 8, minHeight: '150vh' }}>
      <Paper elevation={0} sx={{ p: { xs: 3, md: 4 }, mb: 4, borderRadius: 3, backgroundColor: '#f3f6fb' }}>
        <Stack spacing={2}>
          <Typography variant="h4" fontWeight={700}>
            Reports & Intelligence
          </Typography>
          <Typography variant="body1" color="text.secondary">
            Generate mission packs, export predictive summaries, and trace delivery status across recipients.
          </Typography>
          <Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}>
            <Button variant="contained" startIcon={<DownloadIcon />} onClick={() => setRefreshKey(prev => prev + 1)}>
              Fetch latest stats
            </Button>
            <Button variant="outlined" startIcon={<PictureAsPdfIcon />}>
              Export Shift Brief (PDF)
            </Button>
            {error && <Chip color="warning" variant="outlined" label={`Fallback in use: ${error}`} />}
          </Stack>
        </Stack>
      </Paper>

      <Grid container spacing={3}>
        {KPIs.map(card => (
          <Grid item xs={12} sm={6} md={3} key={card.label}>
            <Paper elevation={2} sx={{ p: 3, borderRadius: 2 }}>
              <Stack direction="row" spacing={2} alignItems="center">
                <Box
                  sx={{
                    width: 48,
                    height: 48,
                    borderRadius: 2,
                    backgroundColor: 'rgba(25,118,210,0.08)',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                  }}
                >
                  {card.icon}
                </Box>
                <Box>
                  <Typography variant="body2" color="text.secondary">
                    {card.label}
                  </Typography>
                  <Typography variant="h5" fontWeight={700}>
                    {card.value}
                  </Typography>
                </Box>
              </Stack>
            </Paper>
          </Grid>
        ))}
      </Grid>

      <Grid container spacing={3} sx={{ mt: 1 }}>
        <Grid item xs={12} lg={7}>
          <Paper elevation={2} sx={{ p: 3, borderRadius: 2 }}>
            <Stack direction="row" justifyContent="space-between" alignItems="center" sx={{ mb: 2 }}>
              <Box>
                <Typography variant="h6" fontWeight={600}>
                  Forecast accuracy tracker
                </Typography>
                <Typography variant="body2" color="text.secondary">
                  Overlay of model predictions vs. observed fire activity
                </Typography>
              </Box>
              <Chip label={loading ? 'Refreshing…' : 'Stable'} size="small" />
            </Stack>
            <ChartComponent />
          </Paper>
        </Grid>
        <Grid item xs={12} lg={5}>
          <Paper elevation={2} sx={{ p: 3, borderRadius: 2 }}>
            <Typography variant="h6" fontWeight={600} gutterBottom>
              Intelligence map preview
            </Typography>
            <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
              Snapshot of the operational layer embedded into PDF exports.
            </Typography>
            <MapComponent />
          </Paper>
        </Grid>
      </Grid>

      <Paper elevation={2} sx={{ mt: 3, p: 3, borderRadius: 2 }}>
        <Typography variant="h6" fontWeight={600} gutterBottom>
          Recent Situation Reports
        </Typography>
        <Table size="small">
          <TableHead>
            <TableRow>
              <TableCell>ID</TableCell>
              <TableCell>Region</TableCell>
              <TableCell>Type</TableCell>
              <TableCell>Issued</TableCell>
              <TableCell>Status</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {RECENT_REPORTS.map(report => (
              <TableRow key={report.id}>
                <TableCell>{report.id}</TableCell>
                <TableCell>{report.region}</TableCell>
                <TableCell>{report.type}</TableCell>
                <TableCell>{report.issued}</TableCell>
                <TableCell>
                  <Chip
                    size="small"
                    label={report.status}
                    sx={{
                      backgroundColor:
                        report.status === 'Delivered'
                          ? RISK_COLORS.safe.bg
                          : RISK_COLORS.medium.bg,
                      color:
                        report.status === 'Delivered'
                          ? RISK_COLORS.safe.text
                          : RISK_COLORS.medium.text,
                    }}
                  />
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </Paper>

      <Paper elevation={0} sx={{ mt: 3, p: 3, borderRadius: 2, backgroundColor: '#fff8e1' }}>
        <Typography variant="subtitle1" fontWeight={600} gutterBottom>
          Tip
        </Typography>
        <Typography variant="body2">
          Bundle weather overlays with crew deployment notes before exporting a PDF. Command centers prefer a
          single attachment summarizing both risk and logistics.
        </Typography>
      </Paper>
    </Container>
  )
}

export default Reports
